### PR TITLE
envoimoinscher 3.3.3 + carrier choice fix

### PR DESCRIPTION
**Pull request by lionelto**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
In your file `envoimoinscher.php`, the function uninstall should remove the tab with the ObjectModel, not a SQL request:
```php
$remove_emc_tab = true;
$id_tab = (int)Tab::getIdFromClassName('AdminEnvoiMoinsCher');
if ($id_tab)
{
	$tab = new Tab($id_tab);
	$remove_emc_tab = $tab->delete();
}
```

**Comment by Quetzacoalt91** [comment]
In `envoimoinscher.php`, line 2026:
```
DB::getInstance()->Execute('UPDATE ' . _DB_PREFIX_ . 'carrier SET
                id_reference = '. $lang_data['id_carrier'] .' WHERE id_carrier = '.$lang_data['id_carrier']);
```
You should cast the id_cast with `(int)`

**Comment by Quetzacoalt91** [comment]
In `envoimoinscher.php`, function `hookHeader()`, keep the following URl: 'https://maps.google.com/maps/api/js?sensor=false'

**Comment by bfortabat** [comment]
@Quetzacoalt91 , lionel just answered :)

**Comment by Quetzacoalt91** [comment]
Hi @lionelto,

Thanks, your PR has just been merged and the changes should be available soon.
Please note that the different logos have also been updated by @mathieuesteban.

Best regards

**Comment by lionelto** [comment]
Thank you

**Pull request merged**
